"""Add age column to User table

Revision ID: 27ea38db3b93
Revises: a4125b9f7bd1
Create Date: 2024-03-29 03:51:04.402331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ea38db3b93'
down_revision = 'a4125b9f7bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.String(length=120), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('projects_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['projects_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('files')
    # ### end Alembic commands ###
